Repository wailsapp/wails, pull requests merged in 2022-10, with the labels that each got.

#1936 docs: sync documents
  website/i18n/ja/docusaurus-plugin-content-docs/current/community/links.mdx
  website/i18n/ja/docusaurus-plugin-content-docs/current/community/showcase/riftshare.mdx
  website/i18n/ja/docusaurus-plugin-content-docs/current/community/templates.mdx
  website/i18n/ja/docusaurus-plugin-content-docs/current/guides/dynamic-assets.mdx
  website/i18n/ja/docusaurus-plugin-content-docs/current/guides/ides.mdx
  website/i18n/ja/docusaurus-plugin-content-docs/current/reference/menus.mdx
  website/i18n/ja/docusaurus-plugin-content-docs/current/reference/options.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/community/links.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/community/templates.mdx
  website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/reference/options.mdx
Labels: Documentation

#1961 Sort structs in models.ts.
  v2/internal/binding/binding.go
  v2/internal/binding/binding_test/binding_multiplestructs_test.go
  v2/internal/binding/binding_test/binding_test.go
Labels: Ready For Testing

#1463 #1057 expose ZoomFactor get/set and add the respective windows only options
  v2/cmd/wails/internal/commands/generate/template/base/main.go.tmpl
  v2/cmd/wails/internal/commands/initialise/templates/generate/plain/main.go.tmpl
  v2/internal/frontend/desktop/windows/frontend.go
  v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/ICoreWebView2Controller.go
  v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/chromium.go
  v2/pkg/options/windows/windows.go
  website/docs/reference/options.mdx
Labels: In Progress
