Repository wailsapp/wails, pull requests merged in 2023-04, with the labels that each got.

#2561 update wml events to be parseable
  v3/V3 Changes.md
  v3/examples/drag-n-drop/main.go
  v3/examples/events/main.go
  v3/examples/plain/main.go
  v3/examples/wml/main.go
  v3/internal/runtime/README.md
  v3/internal/runtime/desktop/api/README.md
  v3/internal/runtime/desktop/api/types.d.ts
  v3/internal/runtime/desktop/events.js
  v3/internal/runtime/desktop/events.test.js
  v3/internal/runtime/desktop/main.js
  v3/internal/runtime/desktop/wml.js
  v3/internal/runtime/runtime_debug_desktop_darwin.js
  v3/internal/runtime/runtime_debug_desktop_linux.js
  v3/internal/runtime/runtime_debug_desktop_windows.js
  v3/internal/runtime/runtime_production_desktop_darwin.js
  v3/internal/runtime/runtime_production_desktop_linux.js
  v3/internal/runtime/runtime_production_desktop_windows.js
  v3/pkg/application/application.go
  v3/pkg/application/events.go
  v3/pkg/application/events_test.go
  v3/pkg/application/messageprocessor_events.go
  v3/pkg/application/webview_window.go
Labels: v3

#2546 feat(cli): add Nodejs version in `wails doctor`
  v2/internal/system/system.go
  v2/internal/system/system_darwin.go
  v2/internal/system/system_linux.go
  v2/internal/system/system_windows.go
  website/src/pages/changelog.mdx
Labels: Enhancement, CLI

#2595 Feature/templates/angular15
  website/docs/community/templates.mdx
Labels: reviewed✅

#2593 Update zypper.go (opensuse-tumbleweed)
  v2/internal/system/packagemanager/zypper.go
  website/src/pages/changelog.mdx
Labels: reviewed✅
