Repository wailsapp/wails, pull requests merged in 2025-09, with the labels that each got.

#4569 Bump version to 3.0.0-alpha.69
  v3/internal/runtime/desktop/@wailsio/runtime/package.json
Labels: v3, v3-alpha, runtime, size:XS, lgtm

#4576 Check for empty buffers instead of nil in responsewriter
  v3/UNRELEASED_CHANGELOG.md
  v3/internal/assetserver/webview/responsewriter_darwin.go
Labels: Bug, Documentation, reviewed ✅, MacOS, v3-alpha, size:XS, lgtm

#4585 fix: compilation issue when using react+nextJs application
  v3/UNRELEASED_CHANGELOG.md
  v3/internal/runtime/desktop/@wailsio/runtime/src/contextmenu.ts
Labels: Bug, Documentation, Linux, v3-alpha, runtime, size:XS, lgtm

#4207 Prevent DLL hijacking by setting default DLL directories on initialization
  v2/internal/frontend/desktop/windows/frontend.go
  v2/internal/frontend/desktop/windows/winc/w32/uxtheme.go
  v2/internal/platform/win32/consts.go
  v2/pkg/options/windows/windows.go
  website/src/pages/changelog.mdx
Labels: size:M, lgtm

#4597 fix: v3-alpha wails3 cli installation path
  .github/workflows/nightly-release-v3.yml
  v3/UNRELEASED_CHANGELOG.md
Labels: Bug, Documentation, v3-alpha, size:XS, lgtm

#4588 [V3 Alpha] Improves macOS Window menu support
  v3/UNRELEASED_CHANGELOG.md
  v3/examples/menu/main.go
  v3/pkg/application/menu_darwin.go
Labels: Enhancement, Documentation, MacOS, v3-alpha, size:S, lgtm

#4544 I would like to add Clustta to the showcase page.
  website/docs/community/showcase/clustta.mdx
  website/static/img/showcase/clustta.png
Labels: Documentation, size:S, lgtm

#4566 typo in bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Documentation, size:XS, lgtm
